services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
